
# checkpoint: "/media/D3/tester/reresearch/_plt/propertest/finetune/test.ckpt"
checkpoint: 
  - "./checkpoint/from_hugging_face/chbmit_classifier.ckpt"
  # - "./checkpoint/finetune/chbmit_bin_filt/classifier-v1.ckpt"
  # - "./checkpoint/finetune/chbmit_bin_filt/classifier-v2.ckpt"
  # - "./checkpoint/finetune/chbmit_bin_filt/classifier-v3.ckpt"
  # - "./checkpoint/finetune/chbmit_bin_filt/classifier-v4.ckpt"

device: "cuda:0"
data_dir: "./data/unified_chbmit/test"

pl_cls_version: 2

schema:
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "X"
      - _target_: src.util.dynamic_load
        item: torch.float
      - _target_: src.util.dynamic_load
        item: src.util.data_transform_chbmit_filt
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "y"
      - _target_: src.util.dynamic_load
        item: torch.long
      # - _target_: src.util.dynamic_load
      #   item: src.util.minus_one

batch_size: 16
num_workers: 4
n_class: 1

metrics:
  - balanced_accuracy
  - pr_auc
  - roc_auc

is_binary: True
